### ISSUE TITLE
Controllers Vtex to jade

### ISSUE THREAD

**Issue by leonardoelias** [alvimm/generator-vtex-scaffold#5]
Estou com problemas, para converter esse controler Vtex para jade:

`<vtex.cmc:fullTextSearchBox/>`

Como poderia ser feito ?
Obrigado

**Comment by guilhermemarconi** [comment]
@leonardoelias infelizmente esse nosso generator foi descontinuado.

De qualquer forma, sua dúvida é na hora de gerar o HTML final para a VTEX? Se sim, temos um helper para esses casos, que é o `vtex-controller`. Ele recebe como parâmetro uma string que será inserida no HTML para a VTEX no build e o que for inserido dentro dele (através da endentação) será exibido somente no ambiente local. Ex.:

```pug
+vtex-controller('<vtex.cmc:fullTextSearchBox/>')
  fieldset.busca
    legend Buscar no site
    label Buscar
    select#ftDept66e623cfa12e468eaf64d6fa52d2478e
      option(value='') Todo o site
    input#ftIdx66e623cfa12e468eaf64d6fa52d2478e(type='hidden', value='')
    input#ftBox66e623cfa12e468eaf64d6fa52d2478e.fulltext-search-box.ui-autocomplete-input(type='text', size='20', accesskey='b', autocomplete='off', role='textbox', aria-autocomplete='list', aria-haspopup='true')
    input#ftBtn66e623cfa12e468eaf64d6fa52d2478e.btn-buscar(type='button', value='Buscar')
```

**Comment by leonardoelias** [comment]
Essa duvida mesmo @guilhermemarconi , muito obrigado.
Você teria algum generator, para indicar ?

Muito obrigado :)

**Comment by guilhermemarconi** [comment]
@leandroelias nós descontinuamos esse generator porque criamos um outro internamente e usamos de forma privada.

Este ainda funciona, apesar de não utilizarmos mais na agência. Nós criamos os nossos justamente por encontrarmos dificuldade nesse tipo de conteúdo.

Lembrando que ele não é um espelho exato de um ambiente VTEX, apesar de buscarmos trazer o máximo possível para um ambiente local. De qualquer forma, sempre há casos em que não temos como fugir de testar no ambiente da VTEX.

Temos pretensão de pegarmos o nosso atual e disponibilizarmos para a comunidade, mas ainda não temos um prazo estipulado para isso. Quando fizermos, eu adiciono uma mensagem no README desse aqui para que passem a utilizar o outro. :wink:
